name: py37cmp-gui

channels:
    - conda-forge
    - aramislab
    - mrtrix3

dependencies:
    - python=3.7
    - pip=21.3.1
    - graphviz=2.50.0
    - dipy=1.3.0
    - fsleyes=1.3.3
    - indexed_gzip=1.6.4
    - mrtrix3=3.0.3

    - pip:
          - numpy==1.21.6
          - matplotlib==3.5.2
          - configparser==5.2.0
          - nipype==1.8.0
          - traits==6.3.2
          - traitsui==7.2.0
          - PyQt5==5.15.6
          - duecredit==0.9.1
          - obspy==1.2.2
          - mne==0.24.1
          - mne_connectivity==0.3
          - datalad[full]==0.15.4
          - datalad-container==1.1.5
          - datalad-neuroimaging==0.3.1
          - pybids==0.14.0
          - statsmodels==0.13.1
          - networkx==2.6.3
          - pydicom==2.2.2
          - pycartool==0.1.1
