#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
import os

#import wx
from pyface.qt import QtCore, QtGui


import subprocess


#Traits/traituiQt4
import traitsui.qt4

#BIDS import
from bids.grabbids import BIDSLayout

#CMP imports
from cmp.configurator import gui

from cmp.info import __version__


def info():
    print "\nConnectome Mapper Configurator " + __version__
    print """Copyright (C) 2009-2018, Ecole Polytechnique Fédérale de Lausanne (EPFL) and
             Hospital Center and University of Lausanne (UNIL-CHUV), Switzerland
             All rights reserved.\n"""

def usage():
    print "Usage 1: connectomemapper3-configurator "
    print "Usage 2 (TO BE COMING): connectomemapper3 bids_folder"
    print "Usage 3 (TO BE COMING): connectomemapper3 bids_folder sub-<label> (ses-<label>) "
    print ""
    print "bids_directory <Str> : full path of root directory of bids dataset"
    print "sub-<label> <Str>: subject name"
    print "ses-<label> <Str>: session name"

# Checks the needed dependencies. We call directly the functions instead
# of just checking existence in $PATH in order to handl missing libraries.
# Note that not all the commands give the awaited 1 exit code...
def dep_check():

    nul = open(os.devnull, 'w')

    error = ""

    # TODO try import all dependencies

    if error != "":
        print error
        sys.exit(2)

if __name__ == "__main__":
    # check dependencies
    dep_check()

    # add current directory to the path, useful if DTB_ bins not installed
    os.environ["PATH"] += os.pathsep + os.path.dirname(sys.argv[0])

    # version and copyright message
    info()

    argc = len(sys.argv)
    if argc==1: # no args, launch the GUI
        #traitsui.wx.constants.WindowColor = wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNFACE)
        mw = gui.CMP_MainWindow()
        mw_res = mw.configure_traits()

    else:
        usage()
        sys.exit(2)
