#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
import os
import wx

try: 
    import traitsui.wx
except ImportError: 
    import enthought.traits.ui.wx

import cmp.gui
import cmp.project
from cmp.info import __version__
from cmp.stages.diffusion.cmp_dtb import DTB_gfa

def info():
    print "\nconnectomemapper " + __version__
    print """Copyright (C) 2009-2012, Ecole Polytechnique Fédérale de Lausanne (EPFL) and
             Hospital Center and University of Lausanne (UNIL-CHUV), Switzerland
             All rights reserved.\n"""
          
def usage():
    print "Usage: connectomemapper input_folder ini_file"

if __name__ == "__main__":

    # add current directory to the path, useful if DTB_ bins not installed
    os.environ["PATH"] += os.pathsep + os.path.dirname(sys.argv[0])
    
    # version and copyright message
    info()
    
    argc = len(sys.argv)
    if argc==1: # no args, launch the GUI
        traitsui.wx.constants.WindowColor = wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNFACE)
        mw = cmp.gui.CMP_MainWindow()
        mw_res = mw.configure_traits()
    elif argc==3: # connectomemapper input_folder ini_file
        project = cmp.gui.CMP_Project_Info()
        project.base_directory = os.path.abspath(sys.argv[1])
        project.config_file = os.path.abspath(sys.argv[2])
        pipeline = cmp.project.init_project(project, False)
        if pipeline != None:
            valid_inputs = pipeline.check_input(gui=False)
            if valid_inputs:
                pipeline.process()
            else:
                sys.exit(1)
    else:
        usage()
        sys.exit(2)
